import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'selection_provider.dart';
import 'screens/home_screen.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => SelectionProvider()),
      ],
      child: MaterialApp(
        title: 'Results DG',
        theme: ThemeData.dark().copyWith(
          scaffoldBackgroundColor: const Color(0xFF000033),
        ),
        home: const Scaffold(body: TelaInicial()),
      ),
    );
  }
}
